# 头部菜单，title: link
menu:
  Github: https://github.com/eltonzhong

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/4336248.mp3
  - http://link.hhtjim.com/163/4338461.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '27798d22668192341ae2'
    # 应用秘钥
    clientSecret: 'ccf0e66c06ffc16845926fa2f54a2976e0666979'
    # issue仓库名
    repo: 'eltonZhong.github.io'
    # Github名
    owner: 'EltonZhong'
    # Github名
    admin: ['EltonZhong']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Elton

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 'UA-131070617-1'

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
